### PR TITLE
Updated for submodules

### PR DESCRIPTION
**Pull request by Yuhanun**
WIP

### CODE REVIEW

**Comment by HaicoDorenbos** [comment]
> WIP

Werkgroep Infectie Preventie?

**Comment by RobotJente** [comment]
I'd like to keep this PR on hold for now as it does not add any functional improvements. We can revisit this after the 28th

**Comment by Yuhanun** [comment]
doesn't even compile yet dw

**Comment by Yuhanun** [comment]
Closed for now.

**Pull request closed without merging**
