### PR TITLE
fix the bloody tests

### PR DESCRIPTION
**Pull request by rolfvdhulst**
This gives you a good idea of why we should always double check or TRIPLE check PR's...
Glorious typos

It compiles again, atleast locally. Test server is another thing...

### CODE REVIEW

**Review by JaroKuiken — APPROVED** [review]
Pff, can barely see the difference in upper or lowercase even when its highlighted. Nice one Rolf

**Comment by Yuhanun** [comment]
Fixing docker right now.

**Comment by Yuhanun** [comment]
Okay so "Pull Request" builds are trying to build _current_ development, kind of useless. I'm going to disable that one.

**Comment by Yuhanun** [comment]
LGTM merging.

**Pull request merged**
