### PR TITLE
Remove extra roles for stop formations for 4v4

### PR DESCRIPTION
**Pull request by mamiksik**
### Comments for the reviewer
- 

###### Code Quality
- [x] Is the code is understandable and easy to read
- [?] Changes to the code comply with set clang-format rules
- [x] No use of manual memory control (e.g new/malloc/colloc etc)
- [x] Are (only) smart pointers used?

###### Testing
- [x] All tests are passing.
- [x] I _added new / changed existing_ tests to reflect code changes (state why not otherwise!)
- [x] I tested my changes manually (Describe how, to what extent etc.)

###### Commit Messages
- [x] Commit message is saying what has been changed, **why** it was changed? Remember other developers might not know
  what the problem you are fixing was. Note also negative _decision_ (e.g., why did you not do particular thing)
  **TLDR: Commit message are comprehensive**
- [x] Commit messages follows the rules of https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by emielsteerneman** [comment]
Aren't these rolls needed to give all 11 robots something to do?

**Comment by mamiksik** [comment]
@emielsteerneman well this was intended for Spain. We play only with 4 robots and some of the removed positions overlap for a defensive and aggressive position.

**Comment by alexander-de-ranitz** [comment]
Since we didn't end up merging this before Spain, shall we close this PR Martin?

**Comment by alexander-de-ranitz** [comment]
This PR was intended for Spain, no longer needed

**Pull request closed without merging**
