### PR TITLE
Refactor/roboteam world optimize

### PR DESCRIPTION
**Pull request by Yuhanun**
getRobotsNonOwning is now O(1) instead of O(n)

Solves #781

### CODE REVIEW

**Comment by mrlukasbos** [comment]
I don't see how this solves #781

**Comment by emielsteerneman** [comment]
@mrlukasbos Currently, there is no way to get a RobotView vector of all robots on the field. There is this `std::vector<rtt::world_new::robot::Robot> const &getRobots() const` which does return constants, but not RobotViews. This implements that.

**Review by emielsteerneman — APPROVED** [review]
Looks good, but did you apply the linter?

**Comment by Yuhanun** [comment]
I think I did?

**Comment by emielsteerneman** [comment]
Travis fails, again because of an error in the tests. However, it builds locally and looks solid. Ready to be merged imo.

**Comment by Yuhanun** [comment]
I don't think it's because of the tests, I think it's because it doesn't compile

**Comment by Yuhanun** [comment]
> I don't see how this solves #781

I told paul to go ahead and use getRobotsNonOwning() already even though it would allocate and create an O(n) copy, now it's O(1), i told him to make the issue for that

**Comment by emielsteerneman** [comment]
> I don't think it's because of the tests, I think it's because it doesn't compile

Yeah that's what I meant, my bad. An error in the code of the test, giving a compile error

**Comment by emielsteerneman** [comment]
Well that works I guess, but I'm not reassured knowing that some tests aren't used

**Pull request merged**
