### PR TITLE
Synchronize/utils angle

### PR DESCRIPTION
**Pull request by HaicoDorenbos**
This PR is related to Design/angle #73 on the Roboteam_utils branch. It should be merged first before Design/angle #73 is merged.

### CODE REVIEW

**Review by timovdk — APPROVED** [review]
Looks good but can you please branch from development next time  because it is not clear what commits are actually relevant for this PR

**Comment by HaicoDorenbos** [comment]
> Looks good but can you please branch from development next time because it is not clear what commits are actually relevant for this PR

I will do it next time...

**Comment by HaicoDorenbos** [comment]
Wait with merging this PR, somethings don't compile anymore so I will fix them first

**Comment by HaicoDorenbos** [comment]
Everything should be fixed by now

**Review by rttwente — APPROVED** [review]

**Pull request merged**
